// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using app.Data;

#nullable disable

namespace app.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250730131108_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("app.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "High-performance laptop with 16GB RAM and 512GB SSD",
                            Name = "Laptop"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Cotton t-shirt, available in multiple colors",
                            Name = "T-Shirt"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Learn C# programming with practical examples",
                            Name = "Programming Book"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Latest smartphone with 6.7-inch display and 5G connectivity",
                            Name = "Smartphone"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Tablette 10 pouces avec écran haute résolution et autonomie longue durée",
                            Name = "Tablette"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Auriculares Bluetooth con cancelación de ruido y 24 horas de batería",
                            Name = "Auriculares Inalámbricos"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Fitness tracking horloge met hartslagmeter en GPS",
                            Name = "Smartwatch"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Console de jeu nouvelle génération avec capacités gaming 4K",
                            Name = "Console de Jeu"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Altavoz portátil con sonido 360 grados y diseño resistente al agua",
                            Name = "Altavoz Bluetooth"
                        },
                        new
                        {
                            Id = 10,
                            Description = "DSLR camera met 24MP sensor en 4K video opname",
                            Name = "Digitale Camera"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Moniteur 4K 27 pouces avec support HDR",
                            Name = "Moniteur"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Ratón inalámbrico ergonómico con botones personalizables",
                            Name = "Ratón Inalámbrico"
                        },
                        new
                        {
                            Id = 13,
                            Description = "RGB mechanisch toetsenbord met aanpasbare schakelaars",
                            Name = "Mechanisch Toetsenbord"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Vaqueros clásicos de mezclilla disponibles en varios cortes y lavados",
                            Name = "Vaqueros"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Pull-over en maille chaude parfait pour les temps froids",
                            Name = "Pull-over"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Waterdichte jas met ademende stof",
                            Name = "Waterproof Jas"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Vestido elegante adecuado para ocasiones formales",
                            Name = "Vestido"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Short confortable pour les activités par temps chaud",
                            Name = "Short"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Pak van 6 katoenen sokken in verschillende kleuren",
                            Name = "Sokken"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Sudadera casual con bolsillo frontal",
                            Name = "Sudadera con Capucha"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Maillot de bain à séchage rapide pour la plage et la piscine",
                            Name = "Maillot de Bain"
                        },
                        new
                        {
                            Id = 22,
                            Description = "Zachte geweven sjaal voor extra warmte en stijl",
                            Name = "Sjaal"
                        },
                        new
                        {
                            Id = 23,
                            Description = "Guantes compatibles con pantalla táctil para uso en invierno",
                            Name = "Guantes"
                        },
                        new
                        {
                            Id = 24,
                            Description = "Leer Python programmeren met praktische voorbeelden en oefeningen",
                            Name = "Programmeren in Python"
                        },
                        new
                        {
                            Id = 25,
                            Description = "Guía completa de JavaScript para desarrollo web moderno",
                            Name = "JavaScript para Principiantes"
                        },
                        new
                        {
                            Id = 26,
                            Description = "Maîtrisez la programmation Java avec des exemples concrets",
                            Name = "Programmation Java"
                        },
                        new
                        {
                            Id = 27,
                            Description = "Comprehensive guide to C# programming with practical examples",
                            Name = "C# Programming Guide"
                        },
                        new
                        {
                            Id = 28,
                            Description = "Ontwikkel moderne web applicaties met React en Redux",
                            Name = "React Development"
                        },
                        new
                        {
                            Id = 29,
                            Description = "Construye aplicaciones web robustas con Angular y TypeScript",
                            Name = "Desarrollo con Angular"
                        },
                        new
                        {
                            Id = 30,
                            Description = "Créez des applications web interactives avec Vue.js et Vuex",
                            Name = "Développement Web avec Vue.js"
                        },
                        new
                        {
                            Id = 31,
                            Description = "Leer database ontwerp en SQL optimalisatie technieken",
                            Name = "Database Design"
                        },
                        new
                        {
                            Id = 32,
                            Description = "Fundamentos de algoritmos y estructuras de datos en programación",
                            Name = "Algoritmos y Estructuras de Datos"
                        },
                        new
                        {
                            Id = 33,
                            Description = "Introduction au machine learning avec Python et scikit-learn",
                            Name = "Machine Learning en Python"
                        },
                        new
                        {
                            Id = 34,
                            Description = "Cafetera programable con jarra térmica",
                            Name = "Cafetera"
                        },
                        new
                        {
                            Id = 35,
                            Description = "Mixeur haute puissance pour smoothies et transformation alimentaire",
                            Name = "Mixeur"
                        },
                        new
                        {
                            Id = 36,
                            Description = "4-slice broodrooster met meerdere bruiningsinstellingen",
                            Name = "Broodrooster"
                        },
                        new
                        {
                            Id = 37,
                            Description = "Microondas de encimera con múltiples funciones de cocción",
                            Name = "Horno Microondas"
                        },
                        new
                        {
                            Id = 38,
                            Description = "Service de 24 couverts en acier inoxydable",
                            Name = "Service de Couverts"
                        },
                        new
                        {
                            Id = 39,
                            Description = "Anti-aanbak kookpot set met glazen deksels",
                            Name = "Kookpot Set"
                        },
                        new
                        {
                            Id = 40,
                            Description = "Cojines decorativos para sofá y cama",
                            Name = "Cojín Decorativo"
                        },
                        new
                        {
                            Id = 41,
                            Description = "Parure de lit en coton doux avec housse de couette et taies d'oreiller",
                            Name = "Parure de Lit"
                        },
                        new
                        {
                            Id = 42,
                            Description = "Set van 6 absorberende katoenen badhanddoeken",
                            Name = "Handdoeken Set"
                        },
                        new
                        {
                            Id = 43,
                            Description = "Alfombra suave para mejorar tu espacio de vida",
                            Name = "Alfombra"
                        },
                        new
                        {
                            Id = 44,
                            Description = "Zapatillas ligeras para correr con suela acolchada",
                            Name = "Zapatillas de Running"
                        },
                        new
                        {
                            Id = 45,
                            Description = "Tapis de yoga antidérapant avec sangle de transport",
                            Name = "Tapis de Yoga"
                        },
                        new
                        {
                            Id = 46,
                            Description = "Set van verstelbare halters voor thuis workouts",
                            Name = "Halters"
                        },
                        new
                        {
                            Id = 47,
                            Description = "Raqueta de tenis profesional con funda de transporte",
                            Name = "Raqueta de Tenis"
                        },
                        new
                        {
                            Id = 48,
                            Description = "Ballon de basketball taille et poids officiels",
                            Name = "Ballon de Basketball"
                        },
                        new
                        {
                            Id = 49,
                            Description = "Lichtgewicht fietshelm met verstelbare pasvorm",
                            Name = "Fietshelm"
                        },
                        new
                        {
                            Id = 50,
                            Description = "Rastreador de actividad con monitoreo de frecuencia cardíaca",
                            Name = "Monitor de Actividad"
                        },
                        new
                        {
                            Id = 51,
                            Description = "Set complet de clubs de golf pour débutants",
                            Name = "Clubs de Golf"
                        },
                        new
                        {
                            Id = 52,
                            Description = "All-mountain snowboard voor gevorderde rijders",
                            Name = "Snowboard"
                        },
                        new
                        {
                            Id = 53,
                            Description = "Gafas de natación anti-empañamiento con protección UV",
                            Name = "Gafas de Natación"
                        },
                        new
                        {
                            Id = 54,
                            Description = "Aspiradora portátil para interiores de automóviles",
                            Name = "Aspiradora para Coche"
                        },
                        new
                        {
                            Id = 55,
                            Description = "Caméra de tableau de bord HD avec capacité de vision nocturne",
                            Name = "Caméra de Tableau de Bord"
                        },
                        new
                        {
                            Id = 56,
                            Description = "Verstelbare telefoonhouder voor autodashboard of voorruit",
                            Name = "Auto Telefoonhouder"
                        },
                        new
                        {
                            Id = 57,
                            Description = "Arrancador portátil con linterna integrada",
                            Name = "Arrancador Portátil"
                        },
                        new
                        {
                            Id = 58,
                            Description = "Manomètre de pression des pneus numérique avec écran rétroéclairé",
                            Name = "Manomètre de Pneu"
                        },
                        new
                        {
                            Id = 59,
                            Description = "Premium autowas voor langdurige glans en bescherming",
                            Name = "Autowas"
                        },
                        new
                        {
                            Id = 60,
                            Description = "Funda impermeable para protección en todo tipo de clima",
                            Name = "Funda para Coche"
                        },
                        new
                        {
                            Id = 61,
                            Description = "Housses de siège universelles avec résistance aux taches",
                            Name = "Housses de Siège"
                        },
                        new
                        {
                            Id = 62,
                            Description = "All-weather floor mats with anti-slip backing",
                            Name = "Floor Mats"
                        },
                        new
                        {
                            Id = 63,
                            Description = "GPS navigation system with real-time traffic updates",
                            Name = "GPS Navigator"
                        },
                        new
                        {
                            Id = 64,
                            Description = "Gentle facial cleanser for all skin types",
                            Name = "Facial Cleanser"
                        },
                        new
                        {
                            Id = 65,
                            Description = "Hydrating face moisturizer with SPF protection",
                            Name = "Moisturizer"
                        },
                        new
                        {
                            Id = 66,
                            Description = "Professional-grade hair dryer with multiple heat settings",
                            Name = "Hair Dryer"
                        },
                        new
                        {
                            Id = 67,
                            Description = "Complete makeup set with brushes and case",
                            Name = "Makeup Set"
                        },
                        new
                        {
                            Id = 68,
                            Description = "Luxurious fragrance with long-lasting scent",
                            Name = "Perfume"
                        },
                        new
                        {
                            Id = 69,
                            Description = "Ceramic hair straightener with adjustable temperature",
                            Name = "Hair Straightener"
                        },
                        new
                        {
                            Id = 70,
                            Description = "Hydrating sheet masks for weekly skin treatment",
                            Name = "Face Mask"
                        },
                        new
                        {
                            Id = 71,
                            Description = "Set of 10 nail polishes in trendy colors",
                            Name = "Nail Polish Set"
                        },
                        new
                        {
                            Id = 72,
                            Description = "Versatile eyeshadow palette with matte and shimmer finishes",
                            Name = "Eyeshadow Palette"
                        },
                        new
                        {
                            Id = 73,
                            Description = "Precision beard trimmer with multiple length settings",
                            Name = "Beard Trimmer"
                        },
                        new
                        {
                            Id = 74,
                            Description = "Daily multivitamin supplements for overall health",
                            Name = "Vitamin Supplements"
                        },
                        new
                        {
                            Id = 75,
                            Description = "Digital bathroom scale with body composition analysis",
                            Name = "Digital Scale"
                        },
                        new
                        {
                            Id = 76,
                            Description = "Home blood pressure monitor with irregular heartbeat detection",
                            Name = "Blood Pressure Monitor"
                        },
                        new
                        {
                            Id = 77,
                            Description = "Comprehensive first aid kit for home and travel",
                            Name = "First Aid Kit"
                        },
                        new
                        {
                            Id = 78,
                            Description = "Deep tissue massage gun with multiple attachments",
                            Name = "Massage Gun"
                        },
                        new
                        {
                            Id = 79,
                            Description = "Electric heating pad with multiple heat settings",
                            Name = "Heating Pad"
                        },
                        new
                        {
                            Id = 80,
                            Description = "Set of resistance bands for strength training",
                            Name = "Resistance Bands"
                        },
                        new
                        {
                            Id = 81,
                            Description = "Whey protein powder for post-workout recovery",
                            Name = "Protein Powder"
                        },
                        new
                        {
                            Id = 82,
                            Description = "Contoured sleep mask for better rest",
                            Name = "Sleep Mask"
                        },
                        new
                        {
                            Id = 83,
                            Description = "Textured foam roller for muscle recovery",
                            Name = "Foam Roller"
                        },
                        new
                        {
                            Id = 84,
                            Description = "Family board game for ages 8 and up",
                            Name = "Board Game"
                        },
                        new
                        {
                            Id = 85,
                            Description = "Creative building blocks set for children",
                            Name = "Building Blocks"
                        },
                        new
                        {
                            Id = 86,
                            Description = "1000-piece jigsaw puzzle with scenic design",
                            Name = "Puzzle"
                        },
                        new
                        {
                            Id = 87,
                            Description = "High-speed remote control car for off-road racing",
                            Name = "Remote Control Car"
                        },
                        new
                        {
                            Id = 88,
                            Description = "Soft plush stuffed animal for children",
                            Name = "Stuffed Animal"
                        },
                        new
                        {
                            Id = 89,
                            Description = "Collectible action figure with accessories",
                            Name = "Action Figure"
                        },
                        new
                        {
                            Id = 90,
                            Description = "Fun card game for parties and gatherings",
                            Name = "Card Game"
                        },
                        new
                        {
                            Id = 91,
                            Description = "Mini drone with camera for beginners",
                            Name = "Drone"
                        },
                        new
                        {
                            Id = 92,
                            Description = "STEM learning toy for developing minds",
                            Name = "Educational Toy"
                        },
                        new
                        {
                            Id = 93,
                            Description = "Detailed dollhouse with furniture and accessories",
                            Name = "Doll House"
                        },
                        new
                        {
                            Id = 94,
                            Description = "Premium ruled notebook with hardcover",
                            Name = "Notebook"
                        },
                        new
                        {
                            Id = 95,
                            Description = "Set of 10 gel pens in assorted colors",
                            Name = "Pen Set"
                        },
                        new
                        {
                            Id = 96,
                            Description = "Multi-compartment desk organizer for office supplies",
                            Name = "Desk Organizer"
                        },
                        new
                        {
                            Id = 97,
                            Description = "Heavy-duty stapler with staple remover",
                            Name = "Stapler"
                        },
                        new
                        {
                            Id = 98,
                            Description = "Two-drawer file cabinet for document storage",
                            Name = "File Cabinet"
                        },
                        new
                        {
                            Id = 99,
                            Description = "Magnetic whiteboard with marker tray",
                            Name = "Whiteboard"
                        },
                        new
                        {
                            Id = 100,
                            Description = "Cross-cut paper shredder for secure document disposal",
                            Name = "Paper Shredder"
                        },
                        new
                        {
                            Id = 101,
                            Description = "LED desk lamp with adjustable brightness",
                            Name = "Desk Lamp"
                        },
                        new
                        {
                            Id = 102,
                            Description = "500 sheets of premium printer paper",
                            Name = "Printer Paper"
                        },
                        new
                        {
                            Id = 103,
                            Description = "Monthly desk calendar with notes section",
                            Name = "Calendar"
                        });
                });

            modelBuilder.Entity("app.Models.ProductTag", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ProductTag");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            TagId = 1
                        },
                        new
                        {
                            ProductId = 2,
                            TagId = 2
                        },
                        new
                        {
                            ProductId = 3,
                            TagId = 3
                        },
                        new
                        {
                            ProductId = 4,
                            TagId = 1
                        },
                        new
                        {
                            ProductId = 5,
                            TagId = 1
                        },
                        new
                        {
                            ProductId = 6,
                            TagId = 1
                        },
                        new
                        {
                            ProductId = 7,
                            TagId = 1
                        },
                        new
                        {
                            ProductId = 8,
                            TagId = 1
                        },
                        new
                        {
                            ProductId = 9,
                            TagId = 1
                        },
                        new
                        {
                            ProductId = 10,
                            TagId = 1
                        },
                        new
                        {
                            ProductId = 11,
                            TagId = 1
                        },
                        new
                        {
                            ProductId = 12,
                            TagId = 1
                        },
                        new
                        {
                            ProductId = 13,
                            TagId = 1
                        },
                        new
                        {
                            ProductId = 14,
                            TagId = 2
                        },
                        new
                        {
                            ProductId = 15,
                            TagId = 2
                        },
                        new
                        {
                            ProductId = 16,
                            TagId = 2
                        },
                        new
                        {
                            ProductId = 17,
                            TagId = 2
                        },
                        new
                        {
                            ProductId = 18,
                            TagId = 2
                        },
                        new
                        {
                            ProductId = 19,
                            TagId = 2
                        },
                        new
                        {
                            ProductId = 20,
                            TagId = 2
                        },
                        new
                        {
                            ProductId = 21,
                            TagId = 2
                        },
                        new
                        {
                            ProductId = 22,
                            TagId = 2
                        },
                        new
                        {
                            ProductId = 23,
                            TagId = 2
                        },
                        new
                        {
                            ProductId = 24,
                            TagId = 3
                        },
                        new
                        {
                            ProductId = 25,
                            TagId = 3
                        },
                        new
                        {
                            ProductId = 26,
                            TagId = 3
                        },
                        new
                        {
                            ProductId = 27,
                            TagId = 3
                        },
                        new
                        {
                            ProductId = 28,
                            TagId = 3
                        },
                        new
                        {
                            ProductId = 29,
                            TagId = 3
                        },
                        new
                        {
                            ProductId = 30,
                            TagId = 3
                        },
                        new
                        {
                            ProductId = 31,
                            TagId = 3
                        },
                        new
                        {
                            ProductId = 32,
                            TagId = 3
                        },
                        new
                        {
                            ProductId = 33,
                            TagId = 3
                        },
                        new
                        {
                            ProductId = 34,
                            TagId = 4
                        },
                        new
                        {
                            ProductId = 35,
                            TagId = 4
                        },
                        new
                        {
                            ProductId = 36,
                            TagId = 4
                        },
                        new
                        {
                            ProductId = 37,
                            TagId = 4
                        },
                        new
                        {
                            ProductId = 38,
                            TagId = 4
                        },
                        new
                        {
                            ProductId = 39,
                            TagId = 4
                        },
                        new
                        {
                            ProductId = 40,
                            TagId = 4
                        },
                        new
                        {
                            ProductId = 41,
                            TagId = 4
                        },
                        new
                        {
                            ProductId = 42,
                            TagId = 4
                        },
                        new
                        {
                            ProductId = 43,
                            TagId = 4
                        },
                        new
                        {
                            ProductId = 44,
                            TagId = 5
                        },
                        new
                        {
                            ProductId = 45,
                            TagId = 5
                        },
                        new
                        {
                            ProductId = 46,
                            TagId = 5
                        },
                        new
                        {
                            ProductId = 47,
                            TagId = 5
                        },
                        new
                        {
                            ProductId = 48,
                            TagId = 5
                        },
                        new
                        {
                            ProductId = 49,
                            TagId = 5
                        },
                        new
                        {
                            ProductId = 50,
                            TagId = 5
                        },
                        new
                        {
                            ProductId = 51,
                            TagId = 5
                        },
                        new
                        {
                            ProductId = 52,
                            TagId = 5
                        },
                        new
                        {
                            ProductId = 53,
                            TagId = 5
                        },
                        new
                        {
                            ProductId = 54,
                            TagId = 6
                        },
                        new
                        {
                            ProductId = 55,
                            TagId = 6
                        },
                        new
                        {
                            ProductId = 56,
                            TagId = 6
                        },
                        new
                        {
                            ProductId = 57,
                            TagId = 6
                        },
                        new
                        {
                            ProductId = 58,
                            TagId = 6
                        },
                        new
                        {
                            ProductId = 59,
                            TagId = 6
                        },
                        new
                        {
                            ProductId = 60,
                            TagId = 6
                        },
                        new
                        {
                            ProductId = 61,
                            TagId = 6
                        },
                        new
                        {
                            ProductId = 62,
                            TagId = 6
                        },
                        new
                        {
                            ProductId = 63,
                            TagId = 6
                        },
                        new
                        {
                            ProductId = 64,
                            TagId = 7
                        },
                        new
                        {
                            ProductId = 65,
                            TagId = 7
                        },
                        new
                        {
                            ProductId = 66,
                            TagId = 7
                        },
                        new
                        {
                            ProductId = 67,
                            TagId = 7
                        },
                        new
                        {
                            ProductId = 68,
                            TagId = 7
                        },
                        new
                        {
                            ProductId = 69,
                            TagId = 7
                        },
                        new
                        {
                            ProductId = 70,
                            TagId = 7
                        },
                        new
                        {
                            ProductId = 71,
                            TagId = 7
                        },
                        new
                        {
                            ProductId = 72,
                            TagId = 7
                        },
                        new
                        {
                            ProductId = 73,
                            TagId = 7
                        },
                        new
                        {
                            ProductId = 74,
                            TagId = 8
                        },
                        new
                        {
                            ProductId = 75,
                            TagId = 8
                        },
                        new
                        {
                            ProductId = 76,
                            TagId = 8
                        },
                        new
                        {
                            ProductId = 77,
                            TagId = 8
                        },
                        new
                        {
                            ProductId = 78,
                            TagId = 8
                        },
                        new
                        {
                            ProductId = 79,
                            TagId = 8
                        },
                        new
                        {
                            ProductId = 80,
                            TagId = 8
                        },
                        new
                        {
                            ProductId = 81,
                            TagId = 8
                        },
                        new
                        {
                            ProductId = 82,
                            TagId = 8
                        },
                        new
                        {
                            ProductId = 83,
                            TagId = 8
                        },
                        new
                        {
                            ProductId = 84,
                            TagId = 9
                        },
                        new
                        {
                            ProductId = 85,
                            TagId = 9
                        },
                        new
                        {
                            ProductId = 86,
                            TagId = 9
                        },
                        new
                        {
                            ProductId = 87,
                            TagId = 9
                        },
                        new
                        {
                            ProductId = 88,
                            TagId = 9
                        },
                        new
                        {
                            ProductId = 89,
                            TagId = 9
                        },
                        new
                        {
                            ProductId = 90,
                            TagId = 9
                        },
                        new
                        {
                            ProductId = 91,
                            TagId = 9
                        },
                        new
                        {
                            ProductId = 92,
                            TagId = 9
                        },
                        new
                        {
                            ProductId = 93,
                            TagId = 9
                        },
                        new
                        {
                            ProductId = 94,
                            TagId = 10
                        },
                        new
                        {
                            ProductId = 95,
                            TagId = 10
                        },
                        new
                        {
                            ProductId = 96,
                            TagId = 10
                        },
                        new
                        {
                            ProductId = 97,
                            TagId = 10
                        },
                        new
                        {
                            ProductId = 98,
                            TagId = 10
                        },
                        new
                        {
                            ProductId = 99,
                            TagId = 10
                        },
                        new
                        {
                            ProductId = 100,
                            TagId = 10
                        },
                        new
                        {
                            ProductId = 101,
                            TagId = 10
                        },
                        new
                        {
                            ProductId = 102,
                            TagId = 10
                        },
                        new
                        {
                            ProductId = 103,
                            TagId = 10
                        },
                        new
                        {
                            ProductId = 6,
                            TagId = 4
                        },
                        new
                        {
                            ProductId = 9,
                            TagId = 4
                        },
                        new
                        {
                            ProductId = 34,
                            TagId = 1
                        },
                        new
                        {
                            ProductId = 35,
                            TagId = 1
                        },
                        new
                        {
                            ProductId = 45,
                            TagId = 8
                        },
                        new
                        {
                            ProductId = 46,
                            TagId = 8
                        },
                        new
                        {
                            ProductId = 50,
                            TagId = 8
                        },
                        new
                        {
                            ProductId = 80,
                            TagId = 5
                        },
                        new
                        {
                            ProductId = 8,
                            TagId = 9
                        },
                        new
                        {
                            ProductId = 91,
                            TagId = 1
                        },
                        new
                        {
                            ProductId = 27,
                            TagId = 4
                        },
                        new
                        {
                            ProductId = 50,
                            TagId = 1
                        },
                        new
                        {
                            ProductId = 73,
                            TagId = 8
                        },
                        new
                        {
                            ProductId = 96,
                            TagId = 3
                        });
                });

            modelBuilder.Entity("app.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Books"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Home & Kitchen"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Automotive"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Beauty"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Health"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Toys & Games"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Office Supplies"
                        });
                });

            modelBuilder.Entity("app.Models.ProductTag", b =>
                {
                    b.HasOne("app.Models.Product", "Product")
                        .WithMany("ProductTags")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("app.Models.Tag", "Tag")
                        .WithMany("ProductTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("app.Models.Product", b =>
                {
                    b.Navigation("ProductTags");
                });

            modelBuilder.Entity("app.Models.Tag", b =>
                {
                    b.Navigation("ProductTags");
                });
#pragma warning restore 612, 618
        }
    }
}
